# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-05-07 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_question_tema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='tema',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
