# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-05-07 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190507_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='correcto',
            field=models.BooleanField(default=False),
        ),
    ]
